import cohomology_theory_linear_algebraic_groups_lemma_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace cohomology_theory_linear_algebraic_groups_lemma_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end cohomology_theory_linear_algebraic_groups_lemma_canonical_lane_mathlib
end HautevilleHouse
